blank_issues_enabled: true
contact_links:
  - name: Question / discussion
    url: https://github.com/thiamyatma/archives-concours-uam/discussions
    about: Pour les questions générales, préférez les Discussions aux Issues.
